name: Sequencer Topos-Smart-Contracts

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      topos-ref:
        description: "Git ref of topos"
        required: false
      topos-smart-contracts-ref:
        description: "Git ref of topos-smart-contracts"
        required: false

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -Dwarnings
  RUST_BACKTRACE: 1
  rust_clippy: 1.62.1

jobs:
  topos-metadata:
    uses: ./.github/workflows/util:get-latest-release.yml
    with:
      organization: topos-network
      repository: topos

  contracts-metadata:
    uses: ./.github/workflows/util:get-latest-release.yml
    with:
      organization: topos-network
      repository: topos-smart-contracts

  e2e:
    strategy:
      fail-fast: false
      matrix:
        target:
          - { name: Linux, os: ubuntu-latest, triple: x86_64-unknown-linux-gnu }
        version:
          - stable
          - nightly
    name: ${{ matrix.version }}
    runs-on: ${{ matrix.target.os }}
    env:
      TOPOS_REF: ${{ inputs.topos-ref || needs.topos-metadata.outputs.latest-release }}
      CONTRACTS_REF: ${{ inputs.topos-smart-contracts-ref || needs.contracts-metadata.outputs.latest-release }}
    steps:
      - name: Display stack component versions
        run: >
          echo "topos ref: ${{ env.TOPOS_REF }}" &&
          echo "contracts ref: ${{ env.CONTRACTS_REF }}"

      - name: Checkout topos repo
        uses: actions/checkout@v3
        with:
          repository: topos-network/topos
          ref: ${{ env.TOPOS_REF }}
          path: topos

      - name: Install Rust ${{ matrix.version }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.version }}
          components:
          override: true

      - name: Set up rust cache
        uses: Swatinem/rust-cache@v1

      - name: Install Protoc
        uses: arduino/setup-protoc@v1

      - name: Checkout topos-smart-contracts repo
        uses: actions/checkout@v3
        with:
          repository: topos-network/topos-smart-contracts
          ref: ${{ env.CONTRACTS_REF }}
          path: contracts

      - name: Set up NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
          cache-dependency-path: contracts/package-lock.json

      - name: Install dependencies
        working-directory: contracts
        run: npm ci

      - name: Build contracts
        working-directory: contracts
        run: npm run build

      - name: Move contract artifacts
        run: mv contracts/artifacts topos

      - name: Run all workspace tests
        working-directory: topos
        run: |
          cd crates/topos-sequencer-subnet-runtime
          cargo test -- --nocapture
