name: Sequencer Topos-Smart-Contracts

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      topos-version:
        description: "Version of topos"
        required: false
      topos-smart-contracts-version:
        description: "Version of topos-smart-contracts"
        required: false
      polygon-edge-version:
        description: "Version of polygon-edge"
        required: false

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -Dwarnings
  RUST_BACKTRACE: 1
  rust_clippy: 1.62.1

jobs:
  topos-metadata:
    uses: ./.github/workflows/util:get-latest-release.yml
    with:
      organization: topos-network
      repository: topos

  topos-smart-contracts-metadata:
    uses: ./.github/workflows/util:get-latest-release.yml
    with:
      organization: topos-network
      repository: topos-smart-contracts

  polygon-edge-metadata:
    uses: ./.github/workflows/util:get-latest-release.yml
    with:
      organization: topos-network
      repository: polygon-edge

  e2e:
    strategy:
      fail-fast: false
      matrix:
        target:
          - { name: Linux, os: ubuntu-latest, triple: x86_64-unknown-linux-gnu }
        version:
          - stable
          - nightly
    name: ${{ matrix.version }}
    runs-on: ${{ matrix.target.os }}
    steps:
      - name: Display received versions
        run: >
          echo "topos-latest-release: ${{ needs.topos-metadata.outputs.latest-release }}" &&
          echo "topos-input-version: ${{ inputs.topos-version }}" &&
          echo "topos-smart-contracts-latest-release: ${{ needs.topos-smart-contracts-metadata.outputs.latest-release }}" &&
          echo "topos-smart-contracts-input-version: ${{ inputs.topos-smart-contracts-version }}" &&
          echo "polygon-edge-latest-release: ${{ needs.polygon-edge-metadata.outputs.latest-release }}" &&
          echo "polygon-edge-input-version: ${{ inputs.polygon-edge-version }}"

      - name: Checkout topos repo
        uses: actions/checkout@v3
        with:
          repository: topos-network/topos
          # We use first the optional passed version, and if empty the latest release
          ref: ${{ inputs.topos-version || needs.topos-metadata.outputs.latest-release }}
          path: topos

      - name: Checkout topos-smart-contracts repo
        uses: actions/checkout@v3
        with:
          repository: topos-network/topos-smart-contracts
          # We use first the optional passed version, and if empty the latest release
          ref: ${{ inputs.topos-smart-contracts-version || needs.topos-smart-contracts-metadata.outputs.latest-release }}
          path: topos-smart-contracts

      - name: Checkout polygon-edge repo
        uses: actions/checkout@v3
        with:
          repository: topos-network/polygon-edge
          # We use first the optional passed version, and if empty the latest release
          ref: ${{ inputs.polygon-edge-version || needs.polygon-edge-metadata.outputs.latest-release }}
          path: polygon-edge

      - name: Install Rust ${{ matrix.version }}
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.version }}
          components:
          override: true

      - name: Set up rust cache
        uses: Swatinem/rust-cache@v1

      - name: Install Protoc
        uses: arduino/setup-protoc@v1

      - name: Pull polygon-edge image
        run: |
          docker pull ghcr.io/topos-network/polygon-edge:${{ inputs.polygon-edge-version || needs.polygon-edge-metadata.outputs.latest-release }}

      - name: Run all workspace tests
        working-directory: topos
        run: |
          cd crates/topos-sequencer-subnet-runtime
          cargo test -- --nocapture
